// demoAppointments.ts

import { Appointment } from '../clinic/types/appointmentEvent';

export const demoAppointments: Appointment[] = [
  {
    id: 1,
    date: '2024-09-20',
    startHour: '09:00:00',
    endHour: '09:30:00',
    medicId: 101,
    medicName: 'Dr. Alice Smith',
    patientId: 201,
    patientName: 'John Doe',
    patientImage: 'https://randomuser.me/api/portraits/men/1.jpg',
    details: 'Routine check-up and cleaning.',
    treatment: 'Dental Cleaning',
    involvedTeeth: ['Teeth 12', 'Teeth 14'],
    prescription: '',
    price: 100,
    paid: true,
    status: 'done',
    color: '#4CAF50', // Green for completed
  },
  {
    id: 2,
    date: '2024-09-20',
    startHour: '10:00:00',
    endHour: '10:45:00',
    medicId: 102,
    medicName: 'Dr. Bob Johnson',
    patientId: 202,
    patientName: 'Jane Smith',
    patientImage: 'https://randomuser.me/api/portraits/women/2.jpg',
    details: 'Cavity filling in upper molar.',
    treatment: 'Cavity Filling',
    involvedTeeth: ['Tooth 36'],
    prescription: 'Take ibuprofen if needed.',
    price: 150,
    paid: false,
    status: 'not paid',
    color: '#FFC107', // Amber for not paid
  },
  {
    id: 3,
    date: '2024-09-21',
    startHour: '11:00:00',
    endHour: '12:00:00',
    medicId: 101,
    medicName: 'Dr. Alice Smith',
    patientId: 203,
    patientName: 'Michael Brown',
    patientImage: 'https://randomuser.me/api/portraits/men/3.jpg',
    details: 'Root canal treatment.',
    treatment: 'Root Canal',
    involvedTeeth: ['Tooth 18'],
    prescription: 'Antibiotics for 5 days.',
    price: 300,
    paid: true,
    status: 'done',
    color: '#4CAF50',
  },
  {
    id: 4,
    date: '2024-09-22',
    startHour: '14:00:00',
    endHour: '14:30:00',
    medicId: 103,
    medicName: 'Dr. Clara Lee',
    patientId: 204,
    patientName: 'Emily Davis',
    patientImage: 'https://randomuser.me/api/portraits/women/4.jpg',
    details: 'Teeth whitening session.',
    treatment: 'Teeth Whitening',
    involvedTeeth: [],
    prescription: '',
    price: 200,
    paid: true,
    status: 'done',
    color: '#4CAF50',
  },
  {
    id: 5,
    date: '2024-09-23',
    startHour: '15:00:00',
    endHour: '15:30:00',
    medicId: 102,
    medicName: 'Dr. Bob Johnson',
    patientId: 205,
    patientName: 'William Wilson',
    patientImage: 'https://randomuser.me/api/portraits/men/5.jpg',
    details: 'Emergency appointment for toothache.',
    treatment: 'Emergency Care',
    involvedTeeth: ['Tooth 24'],
    prescription: 'Painkillers and rest.',
    price: 120,
    paid: false,
    status: 'upcoming',
    color: '#2196F3', // Blue for upcoming
  },
  {
    id: 6,
    date: '2024-09-24',
    startHour: '09:30:00',
    endHour: '10:00:00',
    medicId: 101,
    medicName: 'Dr. Alice Smith',
    patientId: 206,
    patientName: 'Olivia Martinez',
    patientImage: 'https://randomuser.me/api/portraits/women/6.jpg',
    details: 'Initial consultation for orthodontics.',
    treatment: 'Orthodontic Consultation',
    involvedTeeth: [],
    prescription: '',
    price: 80,
    paid: true,
    status: 'done',
    color: '#4CAF50',
  },
  {
    id: 7,
    date: '2024-09-24',
    startHour: '11:00:00',
    endHour: '11:30:00',
    medicId: 103,
    medicName: 'Dr. Clara Lee',
    patientId: 207,
    patientName: 'Liam Garcia',
    patientImage: 'https://randomuser.me/api/portraits/men/7.jpg',
    details: 'Follow-up after dental implant.',
    treatment: 'Dental Implant Follow-up',
    involvedTeeth: ['Tooth 14'],
    prescription: '',
    price: 90,
    paid: true,
    status: 'done',
    color: '#4CAF50',
  },
  {
    id: 8,
    date: '2024-09-25',
    startHour: '13:00:00',
    endHour: '13:45:00',
    medicId: 102,
    medicName: 'Dr. Bob Johnson',
    patientId: 208,
    patientName: 'Sophia Hernandez',
    patientImage: 'https://randomuser.me/api/portraits/women/8.jpg',
    details: 'Tooth extraction.',
    treatment: 'Tooth Extraction',
    involvedTeeth: ['Tooth 38'],
    prescription: 'Antibiotics and pain management.',
    price: 180,
    paid: false,
    status: 'upcoming',
    color: '#2196F3',
  },
  {
    id: 9,
    date: '2024-09-26',
    startHour: '10:00:00',
    endHour: '10:30:00',
    medicId: 101,
    medicName: 'Dr. Alice Smith',
    patientId: 209,
    patientName: 'James Anderson',
    patientImage: 'https://randomuser.me/api/portraits/men/9.jpg',
    details: 'Routine dental check-up.',
    treatment: 'Dental Check-up',
    involvedTeeth: [],
    prescription: '',
    price: 70,
    paid: true,
    status: 'done',
    color: '#4CAF50',
  },
  {
    id: 10,
    date: '2024-09-27',
    startHour: '16:00:00',
    endHour: '16:30:00',
    medicId: 103,
    medicName: 'Dr. Clara Lee',
    patientId: 210,
    patientName: 'Mia Thomas',
    patientImage: 'https://randomuser.me/api/portraits/women/10.jpg',
    details: 'Gum disease treatment.',
    treatment: 'Periodontal Therapy',
    involvedTeeth: ['Teeth 32', 'Teeth 33', 'Teeth 34'],
    prescription: 'Antiseptic mouthwash.',
    price: 250,
    paid: false,
    status: 'upcoming',
    color: '#2196F3',
  },
  {
    id: 11,
    date: '2024-09-28',
    startHour: '09:00:00',
    endHour: '09:45:00',
    medicId: 102,
    medicName: 'Dr. Bob Johnson',
    patientId: 211,
    patientName: 'Noah Jackson',
    patientImage: 'https://randomuser.me/api/portraits/men/11.jpg',
    details: 'Adjustments to braces.',
    treatment: 'Orthodontic Adjustment',
    involvedTeeth: [],
    prescription: '',
    price: 60,
    paid: true,
    status: 'done',
    color: '#4CAF50',
  },
  {
    id: 12,
    date: '2024-09-29',
    startHour: '14:30:00',
    endHour: '15:15:00',
    medicId: 101,
    medicName: 'Dr. Alice Smith',
    patientId: 212,
    patientName: 'Ava White',
    patientImage: 'https://randomuser.me/api/portraits/women/12.jpg',
    details: 'Dental crown placement.',
    treatment: 'Crown Placement',
    involvedTeeth: ['Tooth 46'],
    prescription: '',
    price: 400,
    paid: false,
    status: 'upcoming',
    color: '#2196F3',
  },
  {
    id: 13,
    date: '2024-09-30',
    startHour: '10:15:00',
    endHour: '10:45:00',
    medicId: 103,
    medicName: 'Dr. Clara Lee',
    patientId: 213,
    patientName: 'Ethan Harris',
    patientImage: 'https://randomuser.me/api/portraits/men/13.jpg',
    details: 'Nightguard fitting.',
    treatment: 'Nightguard Fitting',
    involvedTeeth: [],
    prescription: '',
    price: 130,
    paid: true,
    status: 'done',
    color: '#4CAF50',
  },
  {
    id: 14,
    date: '2024-10-01',
    startHour: '12:00:00',
    endHour: '12:30:00',
    medicId: 102,
    medicName: 'Dr. Bob Johnson',
    patientId: 214,
    patientName: 'Isabella Martin',
    patientImage: 'https://randomuser.me/api/portraits/women/14.jpg',
    details: 'Dental bridge consultation.',
    treatment: 'Bridge Consultation',
    involvedTeeth: ['Teeth 22', 'Teeth 23'],
    prescription: '',
    price: 220,
    paid: false,
    status: 'upcoming',
    color: '#2196F3',
  },
  {
    id: 15,
    date: '2024-10-02',
    startHour: '09:00:00',
    endHour: '09:30:00',
    medicId: 101,
    medicName: 'Dr. Alice Smith',
    patientId: 215,
    patientName: 'Lucas Thompson',
    patientImage: 'https://randomuser.me/api/portraits/men/15.jpg',
    details: 'Initial consultation for dentures.',
    treatment: 'Dentures Consultation',
    involvedTeeth: [],
    prescription: '',
    price: 90,
    paid: true,
    status: 'done',
    color: '#4CAF50',
  },
];
